apiVersion: v1
kind: Service
metadata:
  name: {{ include "rawfilesh-csi.fullname" . }}-controller
  labels:
    {{- include "rawfilesh-csi.labels" . | nindent 4 }}
    component: controller
spec:
  type: ClusterIP
  selector:
    {{- include "rawfilesh-csi.selectorLabels" . | nindent 4 }}
    component: controller
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rawfilesh-csi.fullname" . }}-controller
spec:
  replicas: 1
  serviceName: {{ include "rawfilesh-csi.fullname" . }}
  selector:
    matchLabels: &selectorLabels
      {{- include "rawfilesh-csi.selectorLabels" . | nindent 6 }}
      component: controller
  template:
    metadata:
      labels: *selectorLabels
    spec:
      serviceAccount: {{ include "rawfilesh-csi.fullname" . }}-driver
      priorityClassName: system-cluster-critical
      tolerations:
        - key: "node-role.kubernetes.io/master"
          operator: Equal
          value: "true"
          effect: NoSchedule
      volumes:
        - name: socket-dir
          emptyDir: {}
        - name: data-dir
          {{- toYaml .Values.sharedStorage | nindent 10 }}
      containers:
        - name: csi-driver
          image: "{{ .Values.controller.image.repository }}:{{ .Values.controller.image.tag }}"
          imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
          env:
            - name: PROVISIONER_NAME
              value: "{{ .Values.provisionerName }}"
            - name: CSI_ENDPOINT
              value: unix:///csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
            - name: data-dir
              mountPath: /data
          ports:
            - name: csi-probe
              containerPort: 9808
          resources:
            {{- toYaml .Values.controller.resources | nindent 12 }}
        - name: external-provisioner
          image: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2
          imagePullPolicy: IfNotPresent
          args:
            - "--csi-address=$(ADDRESS)"
            - "--feature-gates=Topology=true"
            - "--strict-topology"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: external-resizer
          image: k8s.gcr.io/sig-storage/csi-resizer:v1.2.0
          imagePullPolicy: IfNotPresent
          args:
            - "--csi-address=$(ADDRESS)"
            - "--handle-volume-inuse-error=false"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
        - name: external-attacher
          image: k8s.gcr.io/sig-storage/csi-attacher:v3.2.1
          imagePullPolicy: IfNotPresent
          args:
            - "--csi-address=$(ADDRESS)"
            - "-stderrthreshold=INFO"
            - "-v=2"
          env:
            - name: ADDRESS
              value: /csi/csi.sock
          volumeMounts:
            - name: socket-dir
              mountPath: /csi
